### ISSUE TITLE
Error when trying to load theme

### ISSUE THREAD

**Issue by korrat** [dawikur/base16-vim-airline-themes#1]
When I try to load the `base16_3024.vim` theme, vim complains about the `{s:scheme_slug}` in line 7.

**Comment by dawikur** [comment]
This is odd, it's definitely defined in the file in line 5. Is the same problem happening with other scheme? What version of vim are you using?

**Comment by korrat** [comment]
I'm sorry, the problem was on my end. I'm using your templates with [base16-universal-manager](https://github.com/pinpox/base16-universal-manager) and it seems that they are providing a wrong `scheme-slug` variable to the template. Therefore, the variable name in line 7 contains a dot, which seems to trip up vim.

There is already an issue covering this: pinpox/base16-universal-manager#5

**Comment by dawikur** [comment]
No problem, thanks for letting me know.
